version: '3.8'

services:
  django:
    container_name: django_test
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    env_file:
      - .env
    volumes:
      - ${VOLUME_PATH}/media:/usr/src/app/django_test/media
    depends_on:
      - postgres
    ports:
      - ${DJANGO_API_PORT}:8000
    command: sh -c "
      poetry run python3 backend/manage.py makemigrations &&
      poetry run python3 backend/manage.py migrate &&
      poetry run python3 backend/manage.py runserver 0.0.0.0:8000
      "
    networks:
      - default

  postgres:
    container_name: ${POSTGRES_HOST}
    image: postgres:14-alpine
    env_file: .env
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - default

networks:
  default:
    name: django_test
