# Generated by Django 4.2.13 on 2024-05-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesmodel',
            name='image',
            field=models.TextField(help_text='Добавьте картинку', verbose_name='Картинка'),
        ),
    ]
